include("${CMAKE_CURRENT_LIST_DIR}/id.cmake")


if(MSVC)
    if(MSVC_VERSION EQUAL 1200)
        set(ICU_TOOLSET "v60")
    elseif(MSVC_VERSION EQUAL 1300)
        set(ICU_TOOLSET "v70")
    elseif(MSVC_VERSION EQUAL 1310)
        set(ICU_TOOLSET "v71")
    elseif(MSVC_VERSION EQUAL 1400)
        set(ICU_TOOLSET "v80")
    elseif(MSVC_VERSION EQUAL 1500)
        set(ICU_TOOLSET "v90")
    elseif(MSVC_VERSION EQUAL 1600)
        set(ICU_TOOLSET "v100")
    elseif(MSVC_VERSION EQUAL 1700)
        set(ICU_TOOLSET "v110")
    elseif(MSVC_VERSION EQUAL 1800)
        set(ICU_TOOLSET "v120")
    elseif(MSVC_VERSION EQUAL 1900)
        set(ICU_TOOLSET "v140")
    elseif((MSVC_VERSION GREATER_EQUAL 1910) AND (MSVC_VERSION LESS_EQUAL 1919))
        set(ICU_TOOLSET "v141")
	else()
		cmut_fatal("[byd][icu] - msvc version \"${MSVC_VERSION}\" not supported by byd. patch me if you can!")
	endif()
endif()

